# Validate this file: http://docs.travis-ci.com/user/travis-lint/
# Run travis-lint from this repo's root
language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r etc/python/requirements.txt
script:
  - ls -l etc/cron/
# whitelist
branches:
  only:
   - master
   - develop

after_success:
  - chmod 600 .travis/rwizflowy-deployer.pem # this key should have push access
  - eval `ssh-agent` && ssh-add .travis/rwizflowy-deployer.pem
  - ssh-keyscan -t rsa 54.85.131.174 >> ~/.ssh/known_hosts
  - git remote add deploy ssh://rwizflowy@54.85.131.174/home/rwizflowy/git-repos/rwizflowy/
  - git push deploy
